# SpringBoot
spring:
  mvc:
    static-path-pattern: /**  # 静态资源的URL模式，匹配所有路径

  web:
    resources:
      static-locations: classpath:/static/  # 静态资源文件的位置，设置为项目资源路径下的spongeBob/static目录

  thymeleaf:
    cache: false  # 禁用Thymeleaf模板引擎的缓存
    prefix: classpath:/templates/  # 模板文件的前缀路径，指向项目资源路径下的spongeBob/template/html目录
    suffix: .html  # 模板文件的后缀，设置为.html

  datasource:
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    url: jdbc:mysql://localhost:3306/springBoot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8  # 数据库连接URL，指向本地MySQL数据库的spongeBob数据库
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
    type: com.alibaba.druid.pool.DruidDataSource  # 数据源类型为Druid连接池

# MyBatis
mybatis:
  mapper-locations: classpath:spongeBob.mapper/*.xml  # 映射文件的位置，设置为项目资源路径下的spongeBob/mapper目录中的所有xml文件
  type-aliases-package: spongeBob.pojo  # 类型别名的包名，指向项目的spongeBob.pojo包

# Socket
server:
  port: 8080  # 服务器端口号，默认为8080
